### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by dobbelina** [Isayso/PlaylistEditorTV#10]
Many thanks for this! 👍 

I hope you don't mind me posting this on the kodi forums.
Thread is here: https://forum.kodi.tv/showthread.php?tid=220615&pid=2890364#pid2890364

Here's a download counter for your README.md.
![GitHub Releases (by Release)](https://img.shields.io/github/downloads/Isayso/PlaylistEditorTV/v1.3.6/total)
`![GitHub Releases (by Release)](https://img.shields.io/github/downloads/Isayso/PlaylistEditorTV/v1.3.6/total)`

**Comment by Isayso** [comment]
Many thanks!
For me it was an evening project sitting on my couch for fun. I'm not using IPTV on daily basis, so any suggestion is helpful. And the video playlist, which was the main project, I haven't found any editor out there. 
I can do an empty cell on a  quick fix or a hide column option, or no import setup option.  I will see.
Thanks!

**Comment by dobbelina** [comment]
Awesome!

Looking forward to it.
