### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by dobbelina** [Isayso/PlaylistEditorTV#11]
1. Ability to de-select or remove columns would be nice.
most kodi playlists don't use all of these.
(tvg-name="Name N/A" tvg-id="id N/A")
Clutters the playlist.
If not doable, at least remove the default text for an empty tag,
(tvg-name="" tvg-id="")

2. Ability to delete content on multiple selected cells.
Both in regard to columns and rows.

With these corrections your editor would be awesome.

Thanks for a great tool! :wink:

**Comment by Isayso** [comment]
Added a single column UI mode and the ability to hide selected columns. 

To delete selected cell contents not yet. Thats more problematic because empty cells cannot be copied or pasted in full row edit mode.

**Comment by Isayso** [comment]
delete function is working now.

Closed
