### ISSUE TITLE
All links show dead

### ISSUE THREAD

**Issue by fportegies** [Isayso/PlaylistEditorTV#15]
Hi there,
Great tool, exactly what I was looking for! Want to remove lots of dead links from extreme long m3u file of IPTV provider.
But all links show dead/red with PlaylistEdi torTV.
I made also a test.m3u with 2 working and 2 dead links.
This is the test.m3u, in the links there is normally my username/password, I replaced them here so it will not be displayed at github.

#EXTM3U
#EXTINF:-1 tvg-name="NL| NPO 1 FHD HEVC" group-title="NEDERLAND FHD" tvg-logo="http://tv.trexiptv.com:8000/picons/logos/npo1hd.png",NL| NPO 1 FHD HEVC
http://line.protv.cc:8000/username/password/50179
#EXTINF:-1 tvg-name="NL| NPO 2 FHD HEVC" group-title="NEDERLAND FHD" tvg-logo="http://tv.trexiptv.com:8000/picons/logos/npo2hd.png",NL| NPO 2 FHD HEVC
http://line.protv.cc:8000/username/password/50178
#EXTINF:-1 tvg-name="Black Mirror S03 E04" group-title="ENGLISH SERIES" tvg-logo="http://line.protv.cc:8000/images/AfKQ9bm4RVTwyKdE2QfLDGrtVTu_small.jpg",Black Mirror S03 E04
http://line.protv.cc:8000/series/username/password/88651.mp4
#EXTINF:-1 tvg-name="Black Mirror S03 E05" group-title="ENGLISH SERIES" tvg-logo="http://line.protv.cc:8000/images/A4g3nH0kYQpqHv1oHBXuTgRgT5u_small.jpg",Black Mirror S03 E05
http://line.protv.cc:8000/series/username/password/88652.mp4

The list is correctly imported and displayed, with all columns and lines. In settings the check-field points to the "link-column".

- Is the format of the file/links correct to use with Playlist Editor TV?
- Any idea what else can be wrong?

The m3u file of the provider is tested on the same laptop correctly with the IPTV-checker from http://tiny-tools.com/ but that program filters columns out when saving.

Greetings,
Frank

**Comment by Isayso** [comment]
Sorry,
but I don't understand your question exactly. 

I can import your list, but of cause, your password is missing, cannot use or check the links. 

The list looks ok so far. 

The check link function tries to read the first 1k data of a stream, but cannot check if the data is useful. I will take a look in to the check function if I see some problem. It could be possible that a password check can lead to a "no response" result. 
Does vlc runs with these links?

Greetings

**Comment by Isayso** [comment]
Ok, now I understand......

the tiny checker checks the links as valid, my tool doesn't. 
I don't do retries yet. 

Can you give me a working test link? 

Thanks!

**Comment by fportegies** [comment]
The m3u list can be opened in VLC.
Links also run in VLC. (Also in Kodi)
My question is: Why are all links marked red/invalid?
But I understand that debugging is hard without the correct
username/password of the link.

Greetings,
Frank

Op za 26 okt. 2019 18:21 schreef Isayso <notifications@github.com>:

**Comment by fportegies** [comment]
I can give you a working link, but only in a personal message. What's your email address?

**Comment by Isayso** [comment]
uncool22000-isayso@yahoo.com

Thanks

**Comment by fportegies** [comment]
Hi,
Here is a little playlist with some working links. Good luck.
Greetings,
Frank



Op za 26 okt. 2019 22:02 schreef Isayso <notifications@github.com>:

**Comment by Isayso** [comment]
Found the problem and is fixed in next version.
