### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fportegies** [Isayso/PlaylistEditorTV#16]
Perhaps something for the future is to build in a little "progress indicator" to see how much (%) of th he links in a m3u file are checked when scanning for dead links. (Seems that github doesn't have a portion "feature request", therefore I added it as an issue)

**Comment by Isayso** [comment]
I think this is the right place for requests (?)

I've think about a progress indicator too.  Thats a bigger redesign of the methods. I don't know if I will find the time to do it. 

Thanks

**Comment by Isayso** [comment]
Will work in 1.4.1     
A counter window with cancel task function to stop link check.

**Comment by Isayso** [comment]
new release v1.4.1
