### ISSUE TITLE
f4mTester links

### ISSUE THREAD

**Issue by dobbelina** [Isayso/PlaylistEditorTV#18]
Hi again Isayso!,

I have an issue when i want to import a **f4mTester** link.
I understand that it's a plugin link and not http, and therefore can not be
tested with the link-tester.
But it would be preferable if they could be imported anyway, but right now
it's not allowed.
In kodi some links wont play without it, example that don't play:
```
#EXTINF:-1  tvg-logo="https://www.digitaltveurope.com/files/2011/12/BBC-World-News1.jpg",BBC WORLD NEWS
http://ott-cdn.ucom.am/s24/index.m3u8
```
Example that does play:
```
#EXTINF:-1  tvg-logo="https://www.digitaltveurope.com/files/2011/12/BBC-World-News1.jpg",BBC WORLD NEWS 
plugin://plugin.video.f4mTester/?streamtype=HLSRETRY&amp;url=http://ott-cdn.ucom.am/s24/index.m3u8
```
Here's an example playlist found on pastebin: https://pastebin.com/raw/sXRuvvAD

**Comment by Isayso** [comment]
looks like a mixture of IPTV and video playlist.....
Does the whole plugin line has to go into the link column?

**Comment by dobbelina** [comment]
> 
> 
> looks like a mixture of IPTV and video playlist.....
> Does the whole plugin line has to go into the link column?

Yes, exactly as in the example above.
When executing that playlist item in kodi, it opens the url in the
f4mTester addon which can resolve some stubborn streamlinks.

**Comment by Isayso** [comment]
Made a quick test version, I wasn't able to install this f4m plugin so I cannot test it on my system. 
No dead link check, no vlc play, just plain import to the list. 

https://github.com/Isayso/PlaylistEditorTV/blob/master/test/PlaylistEditorIPTV_v1.4.2_TEST1.zip

**Comment by dobbelina** [comment]
Yes, that works perfect.
If you want f4mTester you can get it from my repo:
https://dobbelina.github.io/repository.dobbelina-1.0.0.zip
It's under Video add-ons.
I assume you already got LiveStreamsPro, if not, you got it there as well.

**Comment by dobbelina** [comment]
I now know why f4mTester works on some links.
It adds user agent which some streams require.
Example,
Don't work with only m3u8:
`http://92.43.140.249/s27/04.m3u8`
But with added user agent it does:
`http://92.43.140.249/s27/04.m3u8|User-Agent=Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0`

**Comment by Isayso** [comment]
Found similar with dead link check. Some responds only with user agent set. 
So, the link string has to be
 **plugin........//......;url=http://.....|User-Agent=Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0**

I can add this as a general rule if you like.

**Comment by dobbelina** [comment]
If you use f4mTester you don't need to/shouldn't add user agent, it adds it by itself.
Eg,
`plugin://plugin.video.f4mTester/?streamtype=HLSRETRY&amp;url=http://92.43.140.249/s27/04.m3u8`
But a cool feature maybe would be to have that option,
"add user agent string for m3u8" to http links?
Eg,
`http://92.43.140.249/s27/04.m3u8`
Becomes:
`http://92.43.140.249/s27/04.m3u8|User-Agent=Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0`

Preferably as a context menu option, so that one can add it on a link to link basis.

When trying to play a url that starts with **plugin://** with vlc, 
maybe you can script a pop-up that says, "Plugin links only work in kodi"
And for the link-checker to simply ignore or skip url's that start with **plugin://**

**Comment by Isayso** [comment]
I added a context menu for edit cell (F2)
I have problems with the dead link check. It doesn't work on the http links which needs the User-Agent string. With the string, I disabled it (grey) and without it returns an error (orange). 

https://github.com/Isayso/PlaylistEditorTV/blob/master/test/PlaylistEditorIPTV_v1.4.2_TEST3.zip

**Comment by dobbelina** [comment]
Perhaps a regex that sorts out links that start with "plugin" or contains a pipe
symbol "|", and skip those for the link-check.
This regex does the trick: https://regex101.com/r/9dTjpf/3

I don't know C#, but something like this maybe:
```
string pattern = @"^plugin|[|]";

Regex regex = new Regex(pattern, RegexOptions.Compiled | RegexOptions.IgnoreCase);

string url= "http://77.54.71.66:9981/play/a02j/index.m3u8|User-Agent=Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0";

if(regex.IsMatch(url)
{
  //skip link check
}
```

**Comment by Isayso** [comment]
The problem is that the http link who needs the **|user-agent** string in kodi is recognized as a dead link and therefore marked with orange, despite it works.  
Have no solution yet. 

Not checked links, plugin and user-agent, are now in grey.

**Comment by dobbelina** [comment]
Have a look at this:
https://stackoverflow.com/questions/11841540/setting-the-user-agent-header-for-a-webclient-request

**Comment by Isayso** [comment]
I test the links with a default user agent until now. When I have to iterate through different user agents, the whole process can be very time consuming. Not sure if this kind of annoying process is a good idea to find only a few false negative links?
An optional "deep link check" or so can be a way, right. 
I added a channel switch box in player mode now. If you want to try.

**Comment by dobbelina** [comment]
Nice switch box!
I think it starts to work really nice now.
Having the option to add a user agent with F2 is enough.
If one can change the default in the editbox "Kodi user agent for *.m3u8 files",
even better.
I have one issue when playing plugin links, they open 2-3 instances in kodi
making it restart the stream several times.
Have this pop-up as seen below to.
You can try these working plugin links as i assume you got f4mtester installed.
```
plugin://plugin.video.f4mTester/?streamtype=TSDOWNLOADER&name=[COLOR lime]GreenTV[/COLOR];url=http://rocksat.ddns.net:25461/xmbdp2f8/NyRF5yPNtK/26169

plugin://plugin.video.f4mTester/?streamtype=TSDOWNLOADER&name=[COLOR lime]GreenTV[/COLOR];url=http://rocksat.ddns.net:25461/xmbdp2f8/NyRF5yPNtK/26166

plugin://plugin.video.f4mTester/?name=TWT SULAMERICANA&streamtype=TSDOWNLOADER&amp;url=http://iptv-luxe.com:8789/live/filipemiranda/b5sh0Muzb7/320.ts
```
<img width="537" alt="Untitled" src="https://user-images.githubusercontent.com/46063764/68370599-298d9980-013d-11ea-8534-d725ca969ba1.png">

**Comment by Isayso** [comment]
Thanks for the links, will look into it.

The pop-up window appears only in the debug version, its the response string from kodi. 
I have an issue with kodi 18.4 that the stream stops after 10s only when I send it. Started with kodi itself, its working. That's probably why I haven't noticed a re-send, will look into it. 
Thanks for your help!

**Comment by dobbelina** [comment]
Aha, pop-up is only debug version, understand.
The re-start issue is not a big deal, important is that one can see if the link works.
On rare occasions, when starting a plugin, link it will stop.
But most of the times it plays fine after the "hickup", ha ha 😄

**Comment by Isayso** [comment]
I changed the code that the manually given user string is used for link check. Not sure if the false-invalid reply will be better. Plugin links are not checked and shown in grey. 
New version 1.4.2 is online now. The combobox is not designed for very long lists, so it can be slow to open, but I think its acceptable. 
Have fun!

**Comment by dobbelina** [comment]
Awesome work, thank you!
A big improvement from v1.4.1

**Comment by Isayso** [comment]
Thanks!
Do you think a MRU list would be helpful? I'm doing this for the video editor right now.

**Comment by dobbelina** [comment]
Can't hurt, that's for sure.
Go for it.
