### ISSUE TITLE
Key press - Key press operation failed. There is no row at position #

### ISSUE THREAD

**Issue by Skarmunds** [Isayso/PlaylistEditorTV#25]
Hello! I'm sorting playlist files by channel name and removing rows from full list for specific channels list. Whenever my selection includes last row this error comes up. It does shows new list after removing these rows but saving the full playlist again.
I have to press undo button and clear last rows in other editor. Is this _error_ on my end?
Currently organizing from playlists around 1000 - 5000 lines.

P.S. Using on Windows 7.

**Comment by Isayso** [comment]
Hello, I could verify your error. It appears only after row sorting. Must look into the code, no idea yet. 
This .Net built in row sorting seems to be buggy anyway. When you sort the rows, moving rows doesn't work anymore with no fix so far except re-load of the file.
Thanks!

**Comment by Isayso** [comment]
Hello,
I made some changes, please check the test version and tell me if you find some more issues. Thanks!
 [https://github.com/Isayso/PlaylistEditorTV/blob/master/test/PlaylistEditorIPTV_v1.4.5.zip](url)

**Comment by Isayso** [comment]
I think I found it, please use the 1.4.5 pre-release
