### ISSUE TITLE
VLC Player not found

### ISSUE THREAD

**Issue by rpelletierrefocus** [Isayso/PlaylistEditorTV#28]
Windows 10. VLC is installed in default location. 

C:\Program Files (x86)\VideoLAN\VLC

**Comment by Isayso** [comment]
The method gets the vlc location from the registry

\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\VLC media player

Key is InstallLocation

Please take a look inside your registry if this key is there and inform me. Thanks!

**Comment by Isayso** [comment]
If you had an issue with your local vlc installation, I will close the thread, ok?
