### ISSUE TITLE
Keep links for rtmp live streams

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#32]
Thanks for the repository.
One problem I see is that when uploading a list it keeps only http links and removes the ones with rtmp.
Is there a way to keep them or anyhow they get removed when checking for channel availability?
e.g. rtmp://89.33.78.174/live/livestream

**Comment by Isayso** [comment]
I think I can change this. Can you provide me with some sample data?

**Comment by Isayso** [comment]
Please try it.

[PlaylistEditorIPTV_1.5.1.zip](https://github.com/Isayso/PlaylistEditorTV/files/4773214/PlaylistEditorIPTV_1.5.1.zip)

**Comment by SileC** [comment]
Thanks for looking so quickly on this request. I will check it on Monday. Hopefully it will not remove links when checking them because player cannot play link. Eg rtmp works OK in vlc and gse but not working in iptv smarters.

**Comment by SileC** [comment]
Works excellent. Thanks.
