### ISSUE TITLE
Video link checker

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#34]
I have a link to a TV channel:
http://fnctve-i.akamaihd.net/hls/live/200669/fnctve/HD.m3u8
It works excellent in GSEIptv but only on IOS (iPhone, AppleTV)
I cannot get it to work on any other players or platforms even if I install separate video players.
Not sure what is different but maybe is there a different checker you can use that is not deleting it?

**Comment by Isayso** [comment]
The server is responding with error 403, that means it needs a special setup to grant access. 
E.g. if you want to play these m3u8 links in Kodi, you need to add the user agent, which can be defined in the settings and add to the link with F2 and right click.
The link looks like this afterwards:
http://fnctve-i.akamaihd.net/hls/live/200669/fnctve/HD.m3u8|User-Agent=Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0

Your AppleTV seems to use this special User-Agent which I don't know. 
My Prog uses the User-Agent string for testing, so you can try to modify the Agent in the list and test it. 
Its a little bit like "wrong password" and not easy to solve. In future release I can probably add a "cannot test" answer as a grey color. 
If you find the right User-Agent string, please tell me. Probably somebody else knows the solution?
Thanks and I'm sorry!

**Comment by Isayso** [comment]
I made a test version. The half-dead links are gray now. With Ctrl-click you select all and Shift+Ctrl-click only the orange full dead links. 

[PlaylistEditorIPTV_v1.5.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/4793093/PlaylistEditorIPTV_v1.5.2.zip)

**Comment by SileC** [comment]
Excellent. I will give it a try. BTW how can I type in a cell to make updates? Or this has to be done outside checker? Copy paste (for logos) works OK.

**Comment by SileC** [comment]
Grayed out works ok, it is good as it detects geo blocked channels too.
Still got some channels that show red but work ok.
rtmp://95.77.97.220/live/livestream
rtmp://89.33.78.174/live/livestream
rtmp://rapsodia1.arya.ro/live/rapsodiatv1
I have others, but the problem with those is that they are not broadcasting continuos so you have to do the check at specifc time. Maybe is better in that case that the list has a header for Random transmission. But is there a way to remove themafter selection during deletion? I know is just copy and paste to put them back (if you dont ovewrite the original file).

**Comment by Isayso** [comment]
> Excellent. I will give it a try. BTW how can I type in a cell to make updates? Or this has to be done outside checker? Copy paste (for logos) works OK.

with F2 or a second click in the cell, this can be changed in settings.

I found that rtmp are not responding with the Microsoft web client, I would need a 3rd party dll for this. In the meantime I will select them with gray. 

To add a kind of "do not check" flag to the table is not an easy task. I would probably violate the m3u file structure and need my own data format to save. I will think of it.

**Comment by SileC** [comment]
Sounds OK.
I found another issue, these links pass the check but is actually not working.
http://193.228.153.231:4240/bysid/40
http://193.228.153.231:4240/bysid/100
http://193.228.153.231:4240/bysid/120
http://193.228.153.231:4240/bysid/150

**Comment by Isayso** [comment]
Please try it.

TV Station
http://.......

or

http:.....

alone can be imported via clipboard now. So open file and copy to clipboard. 

Your dead links should be detected better now. 

[PlaylistEditorIPTV_v1.5.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/4804091/PlaylistEditorIPTV_v1.5.2.zip)

**Comment by SileC** [comment]
The checking works much better, still missing some links, but very few. (I used the list above, cleared all gray, orange and went through list).
Other issues: 1. It cannot find my vlc to play links, and vlc is even open in a differnt window.
2. for opening file what is the difference between click and double click? I get same command - open file.
3. When moving mouse over OPEN icon, can you add that Ctrl+N makes new window? Is very important if you want to create a new list to paste into (either orange, gray or make new list). And after you have list open you don't see info on background when opening file.
4. Idea: when deleting broken/gray list can you ask if want to copy to clipboard? this way links can be pasted in a new file for further processing.

**Comment by Isayso** [comment]
1. I'm not sure if I will do this for D&D of txt file. It's probably better to have a visual file inspection of the user bevor import. Otherwise the error handling could be very difficult when you have garbage in the file. 
I cannot detect if the link delivers useful stream data and I set a timeout of 6 seconds, if you have a very slow server behind, thats a problem too. The answer time is very different unfortunately.
2. double click on empty background opens the open dialog
3. did it
4. good idea, will do it

**Comment by SileC** [comment]
Let me know when you have the new version.
Related to vlc, do you know why is not able to find it to play channels? Kodi I did not try.

**Comment by Isayso** [comment]
Oh yes vlc forgot.......  It reads the install path from the registry and starts a new vlc process, not using an open one.  the reg key is
"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"
do you see the "vlc not found" popup?

**Comment by SileC** [comment]
Yes, vlc not found. I will check the registry if I have same path on Win10.

**Comment by SileC** [comment]
VLC not found in Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall 
what location should i look in?
<img width="646" alt="VideoLan" src="https://user-images.githubusercontent.com/23043824/85188772-2af87600-b277-11ea-9b78-58932defa369.PNG">

**Comment by Isayso** [comment]
I see you use the 32bit version of vlc, this uses probably an other location, must check this. 
Thanks for your time!

![Screenshot (109)](https://user-images.githubusercontent.com/35309607/85200620-5fad1180-b2f9-11ea-956e-1c4b245aad40.png)

**Comment by SileC** [comment]
I installed what I got from videolan website, didn't pay attention to the dropdown menu for download.
<img width="473" alt="uninstall vlc" src="https://user-images.githubusercontent.com/23043824/85203821-392dad00-b2de-11ea-80a5-415747eb5d60.PNG">
I will install the 64bit to see if everything OK.

**Comment by Isayso** [comment]
Found that the 32bit version has different Reg keys. Must at least check this and do some popup.

**Comment by Isayso** [comment]
Unfortunately my PC broke, I give you the latest version, with some fixes. If you find something, please notice me, but I'm afraid I will not do anything before next week. Its under warranty, so I cannot repair it myself. Thanks!

[PlaylistEditorIPTV_v1.5.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/4809857/PlaylistEditorIPTV_v1.5.2.zip)

**Comment by SileC** [comment]
Ok. Thanks.

**Comment by Isayso** [comment]
Please take a look at this version. You can now select the orange and the gray links separately. 

[PlaylistEditorIPTV_v1.5.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/4860559/PlaylistEditorIPTV_v1.5.2.zip)
