### ISSUE TITLE
Saved file corrupt after "fill cells from clipboard" 

### ISSUE THREAD

**Issue by viper73** [Isayso/PlaylistEditorTV#35]
Problem when loading an m3u file which was changed by PlaylistEditorTV 1.51.
I could open it. After changing some names and saving, i tried to reopen and got this message:

`
Untreatet exception of the application:

Die Länge darf nicht kleiner als 0 (null) sein.
(The length has not to be 0)
Parametername: length

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Die Länge darf nicht kleiner als 0 (null) sein.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei PlaylistEditor.ClassHelp.GetPartString(String fullstr, String startstr, String endstr)
   bei PlaylistEditor.Form1.importDataset(String filename, Boolean append)
   bei PlaylistEditor.Form1.button_revert_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
PlaylistEditorIPTV
    Assembly-Version: 1.5.1.0.
    Win32-Version: 1.5.1.0.
    CodeBase: file:///C:/Users/Jacques/Desktop/PlaylistEditorTV-master/PlaylistEditorIPTV.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.
`

**Comment by Isayso** [comment]
Thanks for your report!
Unfortunately my development PC is on warranty repair vacation :(   (at least for one full week)
In the other open issue thread you find a 1.5.2 beta version, please try to reproduce the error. 
I'm sorry!

**Comment by Isayso** [comment]
One question, did you use the "import from clipboard" button to edit the file before saving?

**Comment by viper73** [comment]
I hope your pc will be back soon :(

I can reproduce this error with 1.5.2 ... same problem.

This is how i did it:
- load m3u file
- change the Title names of some channels
- i did this with copy and "fill cells from clipboard"

This (clipboard) seems to be the bug. If i change the names only by hand it works.
If i paste with the regular "copy" and "paste" (not the "fill cells from clipboard") it works also.
-> BUT: the keyboard shortcut strg+v does not work, only mouse right klick and klick on paste with the mouse

As soon as i use this "fill cells from clipboard" it produces this bug.

**Comment by Isayso** [comment]
Thanks!
My PC hasn't even been picked up by DELL :(  If you don't buy Premium support you get extra shitty support I guess. 

Thanks for your good bug report, than the bug must be older. 
This copy/paste stuff is very complicated. There are 4 types of it now. Full row, full cell, inside cell and cell region. Each time I have to validate the clipboard for the right type of data to insert or overwrite. So ctrl+c/v is always a different context dependent  command. And at the bottom of the table its prone to errors of trying to add an illegal row. 

So, be patient, sorry for that!

**Comment by Isayso** [comment]
So, here we go. 

Please test the ctrl-c/v part too. I'm not sure if I tested all combinations. Thanks! 

[PlaylistEditorIPTV_v1.5.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/4858239/PlaylistEditorIPTV_v1.5.2.zip)

**Comment by viper73** [comment]
Version 1.5.2 seems to work. I could not reproduce the error on this version, all worked fine.
And the cope/paste (strg+c/v) worked also.
Thank you very much for this fast support!

**Comment by Isayso** [comment]
Your're welcome!

official version will autodetect *fill from clipboard* function. If only one cell is in clipboard and the copy to is a region.

**Comment by Isayso** [comment]
fixed with 1.5.2
