### ISSUE TITLE
Loses colors if trying to resort by header

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#37]
opened an m3u list, checked list and got orange and gray ones. The list was not sorted by country to check on vlc links and pressed sort by country. All colors disappeared and need to rescan.
can you add a channel number and keep scan value in memory for sorting?

**Comment by Isayso** [comment]
Thats true, right now one should do something with the the result of the link check first.
 I will look into it.

**Comment by Isayso** [comment]
I think I will save the scan result and after sorting or moving a row, the saved result will be compared with the rows, so no rescan necessary.

**Comment by Isayso** [comment]
A first debug version.
[PlaylistEditorIPTV_1.5.3DEB.zip](https://github.com/Isayso/PlaylistEditorTV/files/4898841/PlaylistEditorIPTV_1.5.3DEB.zip)
