### ISSUE TITLE
RTMP, color gone during resorting......

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#41]
The latest version 1.5.6 lost this feature to gray out rtmp. Also sorting does not keep colors.....Did you remove all the Features We worked in June?

**Comment by Isayso** [comment]
There was a bug, rtmp was checked twice and therefore marked with orange instead of gray.

The color is not gone after sorting, if you click the check button again its marked with the color again with no extra checking.

**Comment by Isayso** [comment]
I made a quick fix and replaced the 1.5.6 version, you can try it

**Comment by SileC** [comment]
I will do. Thanks.
