### ISSUE TITLE
Move Group or multiple channel at once

### ISSUE THREAD

**Issue by ewwink** [Isayso/PlaylistEditorTV#44]
please add this feature. and I think column 3  should be named a "Group" not "Title".
thanks.

**Comment by Isayso** [comment]
Found a bug in Ctrl-I, otherwise you could use Ctrl-x, Ctrl-I to move a whole block of lines. Will fix it in next version.

**Comment by ewwink** [comment]
great, thank you.

**Comment by Isayso** [comment]
bugfix released. Don't know if I can do this function as a button in UI, because with shortcuts you can bundle rows together. The Move up/down button cannot do this in an easy and logic way (?)
