### ISSUE TITLE
link check timing

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#47]
Is there a way to adjust timing to check links? I have some that takes longer to load(sometimes even 10 sec).

**Comment by Isayso** [comment]
at the moment its fixed to 6 sec timeout, I can put it on the UI, but probably do a test version for you to check it first?

**Comment by SileC** [comment]
I have about 80% of links from same IP being OK and rest red. I could test it.

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_timeouttest.zip](https://github.com/Isayso/PlaylistEditorTV/files/5838486/PlaylistEditorIPTV_timeouttest.zip)

20 s timeout, there can be some Debug popups

**Comment by SileC** [comment]
Using new version it passed all the links that I were loading later. .If adjustable would be even better.

**Comment by Isayso** [comment]
I put it on the setting UI

**Comment by SileC** [comment]
Great.
