### ISSUE TITLE
if last line has different structure, not all columns are shown

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#48]
When opening a file not all headers are ON., I missed once to activate all and when saving it deleted logos. Can you have it start with all on?
Is Name tvg-guide and Name2 the program name?

**Comment by Isayso** [comment]
can you send me the corresponding m3u file for debug?
You can attach it as zip file. Thanks

The names are from the m3u data structure, I use only a Kodi on Linux, its probably on other systems different

**Comment by SileC** [comment]
From what I see the file gets the headers from the fist channel. If you have only group, name and link this is what you get for the entire uploaded file. As I see you add all the columns from beginning and then enter info per line read, Some of my links have group name before logo which is not a problem for the players, but might be a problem for  playlist editor.

**Comment by Isayso** [comment]
The columns are filled according to the tag names, the order should be irrelevant. 

#EXTM3U
#EXTINF:-1  group-title="USA" tvg-logo="https://i.imgur.com/HQhdVG1.png",ABC News

    col[0] = GetPartString(line, "tvg-name=\"", "\"");

     col[1] = GetPartString(line, "tvg-id=\"", "\"");
      
     col[2] = GetPartString(line, "group-title=\"", "\"");
   
     col[3] = GetPartString(line, "tvg-logo=\"", "\"");

If your file has a different structure I need an example.

**Comment by SileC** [comment]
Attached is an m3u with the second line having also a logo.
I put logo before group-name and after and in myiptv shows the logo.
I loaded both (logo before and logo after group name) and playlist editor and i get only 3 columns: group, channel name and link. I think that is because the first channel does not have a logo called out.
[Trial headers.txt](https://github.com/Isayso/PlaylistEditorTV/files/5839800/Trial.headers.txt)

.

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v0.6.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/5848645/PlaylistEditorIPTV_v0.6.2.zip)

Can you do a test, incl. the timeout feature in settings? Thanks

**Comment by SileC** [comment]
It works OK now. I even added new fields, ID... and it picked them up.
Other features I see as good. 
1. Add a column for the counter of channels
2. Insert a column (group, ID...) if not available in the original file
3. Channel numbering (ID) and renumbering 
4. Renaming of channels eg. Name ->change to |Country| Name

**Comment by Isayso** [comment]
1. Do yo have a file with a numbering tag?
2. right click - show all columns - add missing entries 
3. will think about it
4. you can do this with copy/paste. Copy the cell you like, select all cells for paste target, paste. All cells will be changed

**Comment by Isayso** [comment]
fixed in v1.6.2
