### ISSUE TITLE
Feature: Move selected channels to a different group (new or existing)

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#49]
I know that you can rename whole group easy is notepad, but can you add this feature here? Selected channels move to a different group,

**Comment by Isayso** [comment]
Renaming a whole group at once? Right now its renaming one cell, copy it, select the range to rename and paste.  I can do it like select range, F2 and rename all in next version. 

The 2nd part of your question I don't get it right now. You want to move a range of selected rows to a different group? So no Ctrl-c, Ctrl-i ?

**Comment by SileC** [comment]
I am still getting used to how it work. For moving to another group of  some channels: CTRLC new group name + select group field of channels to move (or entire group) + CTRLV. I think that works also for renaming an entire group. Still getting used to the use of F2 to edit a cell. Maybe use a double click to edit cell?

**Comment by Isayso** [comment]
double click is already used for playing in vlc, I will extend F2 key for selected cells

**Comment by SileC** [comment]
Double play in most apps is to edit a cell. You have the play button in top to play specific line. I think is sufficient. Use double click to edit cell.

**Comment by Isayso** [comment]
Usually in datatables it is just typing/single click or F2. You can switch between both options in settings.
