### ISSUE TITLE
Need color adjustment

### ISSUE THREAD

**Issue by SileC** [Isayso/PlaylistEditorTV#54]
I did a change to dark mode of windows and now most of the information is not visible.
Top buttons, can you replace with pictures? Help boxes when hovering in top of buttons are OK.
Line items are showing only if selected - can background and text colors be selected based on Windows personalization?
<img width="849" alt="new layout" src="https://user-images.githubusercontent.com/23043824/109032365-94951380-7693-11eb-98f3-abc58b367555.PNG">

**Comment by Isayso** [comment]
How did you do this? The Buttons are pictures, so don't know what is going on. If I switch to dark mode I don't see any difference.

**Comment by SileC** [comment]
I just personalized my display. Here are some settings
<img width="690" alt="settings" src="https://user-images.githubusercontent.com/23043824/109058727-5870ab80-76b1-11eb-8d0d-2c8e045ad97f.PNG">
<img width="949" alt="Windows explorer header" src="https://user-images.githubusercontent.com/23043824/109059469-49d6c400-76b2-11eb-90c9-6005eaec9aa7.PNG">
<img width="960" alt="Window opened" src="https://user-images.githubusercontent.com/23043824/109059606-6a9f1980-76b2-11eb-9e48-1f944e422fdf.png">

**Comment by Isayso** [comment]
there are no color themes implemented in the code. This is not an easy task for me. I don't see it coming very soon. Sorry!

**Comment by SileC** [comment]
No problem, I can use it as is.

**Comment by Isayso** [comment]
after literally hours of searching I found an explanation for this behavior. In high contrast mode Windows does not show background images I use for the buttons. I have to re-design all buttons with new images as icons, which is several hours work. 
At least I could fix the table colors for next release.

**Comment by SileC** [comment]
Thanks for looking into this. My eyes are also thanking as i have to use the high contrast.

**Comment by Isayso** [comment]
I will work on it step by step, found more quirks, unfortunately after 1.6.4

**Comment by SileC** [comment]
Thanks. It looks like a big problem for Windows because also pictures I put 
in excel are not visible. As of now, I found that with Left Alt+Left Shift+Print Screen you can turn on and off quick.

**Comment by Isayso** [comment]
I made a beta version, please try it, the player buttons are not changed yet.

[PlaylistEditorIPTV_v1.6.5beta.zip](https://github.com/Isayso/PlaylistEditorTV/files/6068209/PlaylistEditorIPTV_v1.6.5beta.zip)

**Comment by SileC** [comment]
It looks EXCELENT. Thanks a lot.
<img width="855" alt="1 6 5" src="https://user-images.githubusercontent.com/23043824/109696633-41bbd000-7b5b-11eb-8190-5b5e68e1f365.PNG">

**Comment by Isayso** [comment]
Your welcome! 
If you find problems, leave me a message.
