### ISSUE TITLE
TV Playlist Editor v1.6.4.0 on Win7 Professional 64bit

### ISSUE THREAD

**Issue by praspp** [Isayso/PlaylistEditorTV#56]
TV Playlist Editor v1.6.4.0 can run on Win7 Professional 64bit?

**Comment by Isayso** [comment]
I never tried, you need .Net 4.6.2 and than it should run. I don't have a Win7 PC and cannot try it.

**Comment by praspp** [comment]
I have Microsoft .NET Framework 4.8 on my system. Playlist Editor TV v1.6.4 does not start. I need to install NET Framework 4.6.2?

**Comment by Isayso** [comment]
I have 4.7.1 and 4.8 running, so I guess 4.7.1 includes the 4.6.2   ?
What is the error message?

**Comment by praspp** [comment]
There is no error message. Nothing happens when I try to run the application.

**Comment by Isayso** [comment]
Beside the .Net version, I don't see any reason why it should not run on Win7 64. I made a installable version, it should in stall missing .net parts. Unfortunately I cannot test it here.
[PlaylistEditorTV_v1.6.5_pub.zip](https://github.com/Isayso/PlaylistEditorTV/files/6289999/PlaylistEditorTV_v1.6.5_pub.zip)

**Comment by praspp** [comment]
Unfortunately, the PlaylistEditorTV_v1.6.5 version also doesn't work when installed. The highest version that works on my system is 1.5.5.

**Comment by Isayso** [comment]
so, the .net version is not the error. I didn't change the .net version.  No idea so far......

**Comment by Isayso** [comment]
Can you try to run the exe with dependency walker? One can see missing dlls with it. Thanks!
https://dependencywalker.com

**Comment by Isayso** [comment]
I made two debug versions. Is one of them running?
The NoC version can look distorted, please ignore that.
[PlaylistEditorIPTV_v1.6.5_NoC.zip](https://github.com/Isayso/PlaylistEditorTV/files/6290753/PlaylistEditorIPTV_v1.6.5_NoC.zip)
[PlaylistEditorIPTV_v1.6.5_4.7.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/6290750/PlaylistEditorIPTV_v1.6.5_4.7.2.zip)

**Comment by praspp** [comment]
> Can you try to run the exe with dependency walker? One can see missing dlls with it. Thanks!
> https://dependencywalker.com

Log after trying to start TV Playlist Editor v1.6.4.0 by dependency walker: 

[PlaylistEditorIPTV v.1.6.4.0_dwi.zip](https://github.com/Isayso/PlaylistEditorTV/files/6290778/PlaylistEditorIPTV.v.1.6.4.0_dwi.zip)

**Comment by praspp** [comment]
> I made two debug versions. Is one of them running?
> The NoC version can look distorted, please ignore that.
> [PlaylistEditorIPTV_v1.6.5_NoC.zip](https://github.com/Isayso/PlaylistEditorTV/files/6290753/PlaylistEditorIPTV_v1.6.5_NoC.zip)
> [PlaylistEditorIPTV_v1.6.5_4.7.2.zip](https://github.com/Isayso/PlaylistEditorTV/files/6290750/PlaylistEditorIPTV_v1.6.5_4.7.2.zip)

Test result:
PlaylistEditorIPTV_v1.6.5_NoC - **It works :)**
PlaylistEditorIPTV_v1.6.5_4.7.2 - It doesn't work.

**Comment by Isayso** [comment]
Ok, so the language cannot be get or set on your system. 
The Dependency walker suggest that the C++ Redistribute package is missing on your system ?
https://www.microsoft.com/en-us/download/details.aspx?id=48145
Please try    sfc / scannow  in cmd shell with admin first.

**Comment by praspp** [comment]
> Ok, so the language cannot be get or set on your system.
> The Dependency walker suggest that the C++ Redistribute package is missing on your system ?
> https://www.microsoft.com/en-us/download/details.aspx?id=48145
> Please try sfc / scannow in cmd shell with admin first.

I have installed Microsoft Visual C ++ 2015 to 2019 Redistributable (x64) - 14.24.28127

**Comment by Isayso** [comment]
as a workaround, I can activate your preferred language direct into the code and send it to you. What language do you like to have?

**Comment by praspp** [comment]
In the system I use Polish language.

**Comment by Isayso** [comment]
I don't have Polish as an option, english, german, russian, french, spanish, so I guess english is ok?

**Comment by praspp** [comment]
English is ok.

**Comment by Isayso** [comment]
I hope it works
[PlaylistEditorIPTV_v1.6.5_eng.zip](https://github.com/Isayso/PlaylistEditorTV/files/6299802/PlaylistEditorIPTV_v1.6.5_eng.zip)

**Comment by praspp** [comment]
This version works fine. Thank you very much for your work. I am closing the issue.
