### ISSUE TITLE
en-EN is an invalid culture identifier

### ISSUE THREAD

**Issue by tnystuen** [Isayso/PlaylistEditorTV#58]
When trying to run PlaylistEditorTV with wine in Debian Buster, I got this error message:

`en-EN is an invalid culture identifier. at System.Globalization.CultureInfo.GetCultureInfo`

There seems to be no Region Settings for wine, so I did not get around this error.

According to this, en-EN is in fact invalid: [Microsoft documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c?redirectedfrom=MSDN)

Opened the solution in Visual Studio and did a global replace "en-EN" -> "en-US". After a rebuild, the program ran fine in wine.

In wine, VLC must be installed first, to be able to start the program.

**Comment by Isayso** [comment]
I fixed it, I'm not so sure for the vlc in wine. Can you try it? 

Test version:
[PlaylistEditorIPTV_v1.6.6.zip](https://github.com/Isayso/PlaylistEditorTV/files/7000154/PlaylistEditorIPTV_v1.6.6.zip)

**Comment by tnystuen** [comment]
It now starts without a problem in wine.

I'm not sure if my reported problem with VLC was correct. After uninstalling VLC, PlaylistEditorIPTV starts as it should.

When trying "play with vlc", I get a message "VLC player not found".

So all is well!

**Comment by Isayso** [comment]
Thanks for finding the bug and testing!
