### ISSUE TITLE
 About language settings and name export may cause loss

### ISSUE THREAD

**Issue by jeulinshiyo** [Isayso/PlaylistEditorTV#60]
Results from translation software

Thank you very much. It's very convenient to write this software

Of course, I have some problems in use. I hope I can give some advice

1. It is set to simplified Chinese in the software, but the fact does not change to simplified Chinese. Is it the software setting or my windows? It should not be a system problem. It may be caused by some setting

2. On the latest version of software 1.66, it is found that the value of name will be lost. It cannot be displayed when importing M3U files. After exporting, the name is lost

**Comment by jeulinshiyo** [comment]
Because the translation software may have some errors, Sorry. The general meaning can be expressed

**Comment by Isayso** [comment]
Can you provide me with some screenshots? 
1. I used a semi-automatic translation software, it's not 100% working.
2. The filename ist lost in UI when you open it with Chinese language? Can you give me a screenshot of the open file dialogue?

Thanks!

**Comment by Isayso** [comment]
Please take a look if the filename is correct now. Thanks

[PlaylistEditorIPTV_v1.6.7d.zip](https://github.com/Isayso/PlaylistEditorTV/files/7574740/PlaylistEditorIPTV_v1.6.7d.zip)

**Comment by Isayso** [comment]
found encoding bug, solved in 1.7
