### ISSUE TITLE
add udp protocol support

### ISSUE THREAD

**Issue by moran-x** [Isayso/PlaylistEditorTV#61]
For a long time I could not understand why my playlist is not loaded into the program, as it turned out, the reason is that all the links in the list are in this format udp://@239.1.17.16:1234 and, as I understand it, the udp protocol is not supported. could you add it?

There is also one more wish, there is a ffprobe program that allows you to get information about the stream, including the name of the channel, this would allow you to automatically rename channels in the lists, or generate a custom name.

**Comment by Isayso** [comment]
Never had links with udp so far.

Can you give me some as an example for testing? 

ffprobe: So you have a list with unnamed links and with ffprobe you get the name?

**Comment by moran-x** [comment]
here is an example file
[239.1.1.x.zip](https://github.com/Isayso/PlaylistEditorTV/files/7955339/239.1.1.x.zip)
when you import it, the error "Wrong data structure!" occurs, but if you replace udp with http in the links, the file will open. and when it opens in the table, there are only two columns of name and url, how to add the rest, such as a logo, a group?

ffprobe: yes, as you will see in my playlist, all channels are without names, the file is obtained by scanning the provider's local network.

**Comment by Isayso** [comment]
I made a quick fix, please try it. Do the links play in vlc? I have a black screen in vlc when I try.

[PlaylistEditorIPTV_v1.6.7d.zip](https://github.com/Isayso/PlaylistEditorTV/files/7957614/PlaylistEditorIPTV_v1.6.7d.zip)

**Comment by moran-x** [comment]
thanks, everything works fine and opens in vlc, your link is unlikely to open because it works within my provider

**Comment by Isayso** [comment]
Do you have a working ffprobe parameter string to get the name?

**Comment by moran-x** [comment]
in python i was getting data like this
ffprobe -v quiet -print_format json -show_programs udp://@239.1.1.1:1234
program output in json format, and then parsing
[data.zip](https://github.com/Isayso/PlaylistEditorTV/files/7959105/data.zip)

**Comment by Isayso** [comment]
Would be service_name tag as the channel name?

**Comment by moran-x** [comment]
yes, this is the name of the channel, again it depends on the service provider, whether he has registered this tag.
I also ran into the problem that ffprobe does not extract data immediately, I had to first connect to the stream in the background for 5-10 seconds, and then extract the json data

**Comment by Isayso** [comment]
ok, I will make a test version an give it to you for testing. Timeouts is always a pain for automatic scripts

**Comment by Isayso** [comment]
I don't have a working stream url with a title from ffprobe to check the code. Do you have some for me?

**Comment by moran-x** [comment]
Unfortunately, I did not find any public address where such information would be.

**Comment by Isayso** [comment]
Please try it. Right click on name cell -> Get Name
[PlaylistEditorIPTV_v1.6.7d.zip](https://github.com/Isayso/PlaylistEditorTV/files/7970132/PlaylistEditorIPTV_v1.6.7d.zip)

**Comment by moran-x** [comment]
At the first start, the item in the menu was, when it was restarted, it disappeared, I did not really have time to check it. How to return it?
![wtf](https://user-images.githubusercontent.com/4858784/151786451-f3b52cd0-4de6-41b4-a33d-3d75e1f4f6d2.png)

**Comment by Isayso** [comment]
like the numbering function, click on the cell where you would like the Name copy to. Column 1 and 5  "Name" and "Name2"

**Comment by moran-x** [comment]
does not work, ffprobe in PATH
![wtf2](https://user-images.githubusercontent.com/4858784/151789387-e02c78f9-244a-450a-9441-c8218c6313db.png)

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.6.7d2.zip](https://github.com/Isayso/PlaylistEditorTV/files/7970622/PlaylistEditorIPTV_v1.6.7d2.zip)
 should work on any cell now. If not, try to copy ffprobe.exe to the program dir

**Comment by moran-x** [comment]
does not work, there is no menu item. Where does the program store the settings?

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.6.7d2.zip](https://github.com/Isayso/PlaylistEditorTV/files/7970839/PlaylistEditorIPTV_v1.6.7d2.zip)
there is no restriction in the menu anymore, the version is 1.6.7.2 in header, thee ffprobe path is not stored in settings

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.6.7.3d.zip](https://github.com/Isayso/PlaylistEditorTV/files/7973554/PlaylistEditorIPTV_v1.6.7.3d.zip)
next try

**Comment by moran-x** [comment]
does not work, does not receive data, even after I connect to the stream and watch it.
`response ffprobe: {}`

**Comment by Isayso** [comment]
not surprised, please try 
ffprobe -v quiet -print_format json -show_programs 

in cmd shell. If you don't get anything, what is the working parameter set and the respond in cmd?

**Comment by moran-x** [comment]
here is an example of a public thread
ffprobe -v quiet -print_format json -show_programs https://okkotv-live.cdnvideo.ru/channel/Sony_Turbo.m3u8
but there is no tag with the name of the channel

and this command returns data, but only within my provider
ffprobe -v quiet -print_format json -show_programs udp://@239.1.1.9:1234

**Comment by moran-x** [comment]
look
https://user-images.githubusercontent.com/4858784/151940321-e5051bbc-6b2e-490b-af1b-48e7a4f364e1.mp4

**Comment by Isayso** [comment]
thanks, the ffprobe process is closing too fast I think.

**Comment by moran-x** [comment]
Great! but here is the codepage
![codepage](https://user-images.githubusercontent.com/4858784/151994127-6b1a219b-d062-41a8-b2e1-a79c4f6ee784.png)

**Comment by Isayso** [comment]
ok.....   will look into it

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.6.7.4d.zip](https://github.com/Isayso/PlaylistEditorTV/files/7981912/PlaylistEditorIPTV_v1.6.7.4d.zip)
next version. Did you see some other UI elements with encoding problems (unicode chars)?

**Comment by moran-x** [comment]
again problems with the codepage

![codepage2](https://user-images.githubusercontent.com/4858784/152089123-a80dc1c7-75b1-412f-b2ed-8397da48ca8b.png)

**Comment by Isayso** [comment]
I use UFT8
Can you write the ffprobe output to a file and give it to me?

**Comment by moran-x** [comment]
default codepage
![default_codepage](https://user-images.githubusercontent.com/4858784/152157230-a8d47b78-09ae-43c0-a499-3bdcad737078.png)

after changing the codepage to utf8 (chcp 65001)
![utf8_codepage](https://user-images.githubusercontent.com/4858784/152157412-eb42aa78-ad93-44e4-9ac8-73aa7adabff4.png)


[data.zip](https://github.com/Isayso/PlaylistEditorTV/files/7986461/data.zip)

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.6.7.5d.zip](https://github.com/Isayso/PlaylistEditorTV/files/7989943/PlaylistEditorIPTV_v1.6.7.5d.zip)
I have set the encoding of the cmd shell to UTF8, lets fingers X

The ffprobe response is really slow, I could not get a crash so far.

**Comment by moran-x** [comment]
works, but only with those channels to which the connection was made, the socket is open

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.6.7.zip](https://github.com/Isayso/PlaylistEditorTV/files/7997555/PlaylistEditorIPTV_v1.6.7.zip)
Please try

**Comment by moran-x** [comment]
nothing has changed, it also hangs if it cannot receive data. and without prior connection does not receive data.


https://user-images.githubusercontent.com/4858784/152468593-b03e63de-6321-4d17-b4cd-3a2c99918c50.mp4

**Comment by Isayso** [comment]
https://user-images.githubusercontent.com/35309607/152597371-a80fe2a4-93e2-4566-9bfa-a3f3aed31392.mp4

I  guess ffprobe crash with your link?

**Comment by moran-x** [comment]
there is no failure. This is not the first time I've written about the fact that getting data from an HTTP link and from UDP is slightly different. for http there is no need to pre-connect to the stream. but for udp, you must first connect to the stream, and then request data using ffprobe.
here is an example
https://docs.microsoft.com/ru-ru/dotnet/api/system.net.sockets.udpclient.receive?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-v8Q2uuBWdnGmaDoNff4_QA&epi=a1LgFw09t88-v8Q2uuBWdnGmaDoNff4_QA&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=(ir__rzsxsshia0kfqxukkk0sohz3zu2xtx0wb9u920av00)(7806)(1243925)(a1LgFw09t88-v8Q2uuBWdnGmaDoNff4_QA)()&irclickid=_rzsxsshia0kfqxukkk0sohz3zu2xtx0wb9u920av00&view=net-6.0

I used about the same code in python to get data about the stream, everything is simple with http links, but there were problems with udp.

**Comment by Isayso** [comment]
I saved the last code in the dev_ffprobe branch, the method is in classhelp GetFFrobeStreamName

**Comment by Isayso** [comment]
at least I could reproduce your "crash" now. Its not a crash, just waits for response indefinitely. I send some data to UPD in advance, no change. 

I did not much with python, but can you give me the code to look at the structure?

**Comment by moran-x** [comment]
https://github.com/moran-x/multicast-scan

**Comment by Isayso** [comment]
the UDP has a 5s timeout, give it a try

[PlaylistEditorIPTV_v1.6.7.7d.zip](https://github.com/Isayso/PlaylistEditorTV/files/8075018/PlaylistEditorIPTV_v1.6.7.7d.zip)

**Comment by moran-x** [comment]
does not receive data, even if it first connects to the stream

**Comment by Isayso** [comment]
do you have a idea how I can test this?

**Comment by moran-x** [comment]
no, unless your ISP broadcasts IPTV in a UDP stream.

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.7d.zip](https://github.com/Isayso/PlaylistEditorTV/files/8104141/PlaylistEditorIPTV_v1.7d.zip)

I made a logfile writer. Pease send me the PlaylistEditorlog.txt file - Thanks

**Comment by moran-x** [comment]
Before connecting to a stream in the IPTV viewer
```
Log Entry : 12:34:33 PM Monday, February 21, 2022
  :
  :PlaylistEditor.ClassHelp.UDPSentRec
 Exception! 239.1.1.8:1234
-------------------------------

Log Entry : 12:34:33 PM Monday, February 21, 2022
  :
  :PlaylistEditor.ClassHelp.GetFFrobeStreamName
 UDP Answer False
-------------------------------
```

After connecting to a stream in the IPTV viewer
```
Log Entry : 12:36:20 PM Monday, February 21, 2022
  :
  :PlaylistEditor.ClassHelp.UDPSentRec
 Exception! 239.1.1.8:1234
-------------------------------

Log Entry : 12:36:20 PM Monday, February 21, 2022
  :
  :PlaylistEditor.ClassHelp.GetFFrobeStreamName
 UDP Answer False
-------------------------------

```

**Comment by Isayso** [comment]
Thanks,  if I understand your program correctly, it is listening to the IP:port for up to 10 s and does not send something, right?

**Comment by moran-x** [comment]
> Спасибо, если я правильно понял вашу программу, она слушает IP:порт до 10 с и ничего не отправляет, так?

Yes
here is an example of working with multicast on c#
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.multicastoption?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-gznHSov7JkK7ScjfW7bitw&epi=a1LgFw09t88-gznHSov7JkK7ScjfW7bitw&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=(ir__rzsxsshia0kfqxukkk0sohz3zu2xt3d9s0u920av00)(7806)(1243925)(a1LgFw09t88-gznHSov7JkK7ScjfW7bitw)()&irclickid=_rzsxsshia0kfqxukkk0sohz3zu2xt3d9s0u920av00&view=net-6.0



> наверное развалится. Если udp что-то получает, он возвращает true, если он не работает, процесс ffprobe не отвечает, и тайм-аут не работает.
> 
> И у копипаст есть проблемы [PlaylistEditorIPTV_v1.7.01d.zip](https://github.com/Isayso/PlaylistEditorTV/files/8119717/PlaylistEditorIPTV_v1.7.01d.zip)

does not work
```
Log Entry : 10:43:20 AM Wednesday, February 23, 2022
  :
  :PlaylistEditor.ClassHelp.GetFFrobeStreamName
 UDP Answer 2 False
-------------------------------
```

**Comment by Isayso** [comment]
[PlaylistEditorIPTV_v1.7.03d.zip](https://github.com/Isayso/PlaylistEditorTV/files/8136274/PlaylistEditorIPTV_v1.7.03d.zip)
next try

**Comment by Isayso** [comment]
cannot fix without working links - closed
