### ISSUE TITLE
support for a large number of tags

### ISSUE THREAD

**Issue by moran-x** [Isayso/PlaylistEditorTV#62]
this page https://github.com/kodi-pvr/pvr.iptvsimple#supported-m3u-and-xmltv-elements lists the tags that can be found in the playlist. but the program cannot add some, such as tvg-chno and tvg-shift. It seems to me that their support does not interfere.

**Comment by Isayso** [comment]
No, its not interfering. It is just a matter of time to implement this.

**Comment by Isayso** [comment]
next version will support all tags.

**Comment by Isayso** [comment]
done in 1.7
