### ISSUE TITLE
EXTVCLOPT

### ISSUE THREAD

**Issue by BPanther** [Isayso/PlaylistEditorTV#65]
Please support the #EXTVLCOPT option for user-agent.

**Comment by Isayso** [comment]
Can you give me an example file?

**Comment by BPanther** [comment]
Here 2 examples:

#EXTINF:-1 tvg-id="DasErste.de" tvg-name="ARD" group-title="IPTV-Germany",ARD
#EXTVLCOPT:http-user-agent=MYUSERAGENT/1.1
http://...
#EXTINF:-1 tvg-id="ARTEDeutsch.de" tvg-name="ARTE HD" group-title="IPTV-Germany",ARTE HD
#EXTVLCOPT:http-user-agent=MYUSERAGENT/1.1
http://...

**Comment by Isayso** [comment]
Is this line always the same in the whole file? What should I do with it?

**Comment by BPanther** [comment]
No, #EXTVLCOPT can have different values, e.g.

#EXTVLCOPT:http-user-agent=MYUSERAGENT/1.0
#EXTVLCOPT:http-user-agent=ANOTHERUSERAGENT/1.1
#EXTVLCOPT:video-filter=invert:croppadd{croptop=50,cropbottom=50}

So i think you can use a new field how tvg-id, but if value empty, then the line for #EXTVLCOPT not included for the selected entry.

**Comment by TangoCash** [comment]
The options are the same as the VLC command line (and preferences) options.
Instead of use:
vlc.exe "D:\videos\v1.avi" --video-filter=invert:croppadd{croptop=50,cropbottom=50}

#EXTM3U
#EXTINF:9,v1.avi
#EXTVLCOPT:video-filter=invert:croppadd{croptop=50,cropbottom=50}
d:\videos\v1.avi

May take a look at:
https://code.videolan.org/videolan/vlc/-/blob/master/src/libvlc-module.c#L2096

**Comment by Isayso** [comment]
A quick shot. Please try it. If you find bugs, send me the corresponding dataset and error description.

[PlaylistEditorIPTV_v1.7.2DEBUG.zip](https://github.com/Isayso/PlaylistEditorTV/files/9508857/PlaylistEditorIPTV_v1.7.2DEBUG.zip)

**Comment by BPanther** [comment]
Looks great, but the cursor keys now don't working at all.

**Comment by Isayso** [comment]
That's .....  no idea why. Will look into it

**Comment by Isayso** [comment]
Next try ;)

[PlaylistEditorIPTV_v1.7.2DEBUG.zip](https://github.com/Isayso/PlaylistEditorTV/files/9530136/PlaylistEditorIPTV_v1.7.2DEBUG.zip)

**Comment by BPanther** [comment]
Wow, great work. Thank you very much. :)

**Comment by Isayso** [comment]
bugfix, not tested for all types of files so far

[PlaylistEditorIPTV_v1.7.2DEBUG.zip](https://github.com/Isayso/PlaylistEditorTV/files/9530338/PlaylistEditorIPTV_v1.7.2DEBUG.zip)

**Comment by BPanther** [comment]
Edit/change of the m3u is now OK, but play with VLC does not working.

**Comment by Isayso** [comment]
I guess I need a working file or vlc option string to test it.

**Comment by BPanther** [comment]
Here a entry from https://github.com/iptv-org/iptv/blob/master/streams/us.m3u


#EXTINF:-1 tvg-id="WGNDT1.us" status="online" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.48",WGN Chicago IL (WGN-TV1) (720p)
#EXTVLCOPT:http-referrer=https://plus.teleup.com/
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.48
https://cdn1-8p.teleuptv.net/3773db6d-881b-4096-b9cc-b4fe99ab68ac/index.m3u8


As you can see, there can be more than one entry #EXTVLCOPT exist. The example needs both for working.

**Comment by Isayso** [comment]
Quick test was ok. Please try it

[PlaylistEditorIPTV_v1.7.2beta.zip](https://github.com/Isayso/PlaylistEditorTV/files/9537574/PlaylistEditorIPTV_v1.7.2beta.zip)

**Comment by Isayso** [comment]
Quick test was ok. Please try it

[PlaylistEditorIPTV_v1.7.2beta.zip](https://github.com/Isayso/PlaylistEditorTV/files/9537574/PlaylistEditorIPTV_v1.7.2beta.zip)

**Comment by BPanther** [comment]
Wow, you're great - it works perfect. Thank you very much. :)

**Comment by Isayso** [comment]
Please test it for a while. I don't use this kind of links, will probably not find bugs.

**Comment by Isayso** [comment]
done in release v1.7.2
