### ISSUE TITLE
The language does not change.

### ISSUE THREAD

**Issue by jezokshe** [Isayso/PlaylistEditorTV#68]
Win 11

I would also like the ability to remove the PLAY (Kodi) button. I think it is not installed for many, like me. I touch and the program hangs.
  And so the best of these, thank you!

**Comment by Isayso** [comment]
For language change it  needs a program restart.
You press the Kodi button on accident? Workaround: If you leave the IP blank, you get an error message immediately. 
Can change this in next version.

**Comment by jezokshe** [comment]
@Isayso I did a restart, set it to all languages, but english remains.
 Thanks and also, I think editing (moving) would be faster and more pleasant if the cursor could drag lines.
  Groups could also be made visually logical. That is, do horizontal division in the program window.
  Well, if you need such ideas))) It is clear that it is easy to say in words, I have no idea how difficult it is. Just thoughts.

**Comment by Isayso** [comment]
Which language do you use? I cannot verify it so far, but I got some scaling issues on Win11 on different screen resolutions, no idea where they come from.
You can move rows with right mouse button clicked. 
Visual formatting of rows would be lost after file saving, but you can give me an example what you have in mind with a file.

**Comment by jezokshe** [comment]
@Isayso PC language - Russian. In the program, I set different ones, but it remains in English.
  As for the right button, I understand, thanks.

**Comment by Isayso** [comment]
I can switch to russian, but I have some unusual screen scaling issues in russian, will look into it.
Please try to delete in appdata/Local/Github_Isayso the Playlisteditor folder to reset settings

**Comment by jezokshe** [comment]
@Isayso Well, similar 
![Снимок экрана 2022-12-09 032725](https://user-images.githubusercontent.com/77186394/206580699-bfe5ef0a-f031-4836-a074-5161a50610fb.png)
It is clear that everything will be in the usual form in the sheet.
  I just didn't quite understand how to create groups, or it seemed difficult

**Comment by jezokshe** [comment]
@Isayso 

> Please try to delete in appdata/Local/Github_Isayso the Playlisteditor folder to reset settings

 Made, no changes, not saved. Okay, that's not a problem for me, I just wanted to let you know.

**Comment by Isayso** [comment]
Please give it a try. Delete the appdata/local/Github_Isayso folder first. If the Kodi IP is empty, the button is disabled now.
If you still cannot switch to russian, can you switch to other languages?
[PlaylistEditorIPTV_v1.7.3b.zip](https://github.com/Isayso/PlaylistEditorTV/files/10193513/PlaylistEditorIPTV_v1.7.3b.zip)

**Comment by jezokshe** [comment]
@Isayso Everything is still in English. Switched to French and Russian

**Comment by Isayso** [comment]
hard coded to ru-RU language
[PlaylistEditorIPTV_v1.7.3ru.zip](https://github.com/Isayso/PlaylistEditorTV/files/10195867/PlaylistEditorIPTV_v1.7.3ru.zip)

**Comment by jezokshe** [comment]
@Isayso All the same ))
  I must report that "Russian" is shown, but the language remains in English. Like this:
![изображение](https://user-images.githubusercontent.com/77186394/206733661-9e60981a-6b34-411c-bf30-cdaa45c0be18.png)

**Comment by Isayso** [comment]
no idea why

**Comment by jezokshe** [comment]
@Isayso Here is my config, with all the folders if it helps. I also have the program in downloads (another HHD disk), and the system is on another
[GitHub_Isayso.zip](https://github.com/Isayso/PlaylistEditorTV/files/10196031/GitHub_Isayso.zip)

**Comment by Isayso** [comment]
Looks ok......

I made an install package, maybe a .Net language dll is missing? 
[PlaylistEditorIPTV_v1.7.3I.zip](https://github.com/Isayso/PlaylistEditorTV/files/10200387/PlaylistEditorIPTV_v1.7.3I.zip)

**Comment by jezokshe** [comment]
@Isayso Yes, it worked!
![PE](https://user-images.githubusercontent.com/77186394/206868138-6b6ed9a4-8b67-43e6-b5af-8261a1258428.gif)

**Comment by Isayso** [comment]
great. If you have some translation corrections, feel free to notice me.

**Comment by jezokshe** [comment]
@Isayso Ok. Horizontal scrollbar - "Горизонтальная полоса прокрутки" or "Горизонтальная прокрутка"
 
 There are still minor errors, some I didn’t even understand what it means: D I’ll compare it with the original and write here

**Comment by jezokshe** [comment]
Doubleclick to play - Двойное нажатие для проигрывания or Играть двойным нажатием
 
And like everything

**Comment by Isayso** [comment]
the automatic translation is horrible, don't know how crazy Chinease will be ;) or Arabic

**Comment by Isayso** [comment]
new release 1.7.3
