### ISSUE TITLE
Win x64

### ISSUE THREAD

**Issue by PasshereDude** [Isayso/PlaylistEditorTV#71]
is PlaylistEditorTV_v1.7.3 als for windows in x64 available?
thx

**Comment by Isayso** [comment]
I'm using it on win 10 and 11 x64, what do you mean exactly?

**Comment by Isayso** [comment]
I removed a "prefer 32bit " flag, please try it.
[PlaylistEditorTV_v1.7.4.zip](https://github.com/Isayso/PlaylistEditorTV/files/11191197/PlaylistEditorTV_v1.7.4.zip)

**Comment by Isayso** [comment]
I guess it is working? So I will close it. Feel free to reopen again.
