### ISSUE TITLE
Maybe stupid question: How do I save only working links to new file?

### ISSUE THREAD

**Issue by devkind39** [Isayso/PlaylistEditorTV#78]
Thank you  to the creator for this cool app. I use the checker successfully to find working versus dead links. But I don't see a way to save only the working links to a new m3u file. Thanks for any suggestion how to do this.

**Comment by Isayso** [comment]
You can delete the bad lines. Down below right of the number of lines is a button to select the lines and than you can delete them at once with "del". 

FYI: I'm not active on github anymore, only on Codeberg 
     On Sunday, October 27, 2024 at 03:24:04 PM GMT+1, devkind39 ***@***.***> wrote:  
 
 


Thank you to the creator for this cool app. I use the checker successfully to find working versus dead links. But I don't see a way to save only the working links to a new m3u file. Thanks for any suggestion how to do this.

**Comment by devkind39** [comment]
Perfect! thanks. I will follow you on codeberg.
